apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: sock-chaos
  namespace: sock-shop
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appkind: "deployment"
    appns: sock-shop
    applabel: 'name=carts-db'
  chaosServiceAccount: pod-network-corruption-sa
  experiments:
  - name: pod-network-corruption
    spec:
      components:
        env:
        # network packet corruption percentage
        - name: NETWORK_PACKET_CORRUPTION_PERCENTAGE
          value: '100' #in percentage
        - name: TOTAL_CHAOS_DURATION
          value: '60'
